// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: stats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetURLStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlId         int32                  `protobuf:"varint,1,opt,name=url_id,json=urlId,proto3" json:"url_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLStatsRequest) Reset() {
	*x = GetURLStatsRequest{}
	mi := &file_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLStatsRequest) ProtoMessage() {}

func (x *GetURLStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLStatsRequest.ProtoReflect.Descriptor instead.
func (*GetURLStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GetURLStatsRequest) GetUrlId() int32 {
	if x != nil {
		return x.UrlId
	}
	return 0
}

func (x *GetURLStatsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetURLStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlStats      []*URLStats            `protobuf:"bytes,1,rep,name=url_stats,json=urlStats,proto3" json:"url_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLStatsResponse) Reset() {
	*x = GetURLStatsResponse{}
	mi := &file_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLStatsResponse) ProtoMessage() {}

func (x *GetURLStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLStatsResponse.ProtoReflect.Descriptor instead.
func (*GetURLStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *GetURLStatsResponse) GetUrlStats() []*URLStats {
	if x != nil {
		return x.UrlStats
	}
	return nil
}

type URLStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlId         int32                  `protobuf:"varint,1,opt,name=url_id,json=urlId,proto3" json:"url_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Clicks        int32                  `protobuf:"varint,5,opt,name=clicks,proto3" json:"clicks,omitempty"`
	BotClicks     int32                  `protobuf:"varint,6,opt,name=bot_clicks,json=botClicks,proto3" json:"bot_clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLStats) Reset() {
	*x = URLStats{}
	mi := &file_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLStats) ProtoMessage() {}

func (x *URLStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLStats.ProtoReflect.Descriptor instead.
func (*URLStats) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{2}
}

func (x *URLStats) GetUrlId() int32 {
	if x != nil {
		return x.UrlId
	}
	return 0
}

func (x *URLStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *URLStats) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *URLStats) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *URLStats) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *URLStats) GetBotClicks() int32 {
	if x != nil {
		return x.BotClicks
	}
	return 0
}

var File_stats_proto protoreflect.FileDescriptor

const file_stats_proto_rawDesc = "" +
	"\n" +
	"\vstats.proto\x12\x05stats\"?\n" +
	"\x12GetURLStatsRequest\x12\x15\n" +
	"\x06url_id\x18\x01 \x01(\x05R\x05urlId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"C\n" +
	"\x13GetURLStatsResponse\x12,\n" +
	"\turl_stats\x18\x01 \x03(\v2\x0f.stats.URLStatsR\burlStats\"\x9e\x01\n" +
	"\bURLStats\x12\x15\n" +
	"\x06url_id\x18\x01 \x01(\x05R\x05urlId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x16\n" +
	"\x06clicks\x18\x05 \x01(\x05R\x06clicks\x12\x1d\n" +
	"\n" +
	"bot_clicks\x18\x06 \x01(\x05R\tbotClicks2T\n" +
	"\fStatsService\x12D\n" +
	"\vGetURLStats\x12\x19.stats.GetURLStatsRequest\x1a\x1a.stats.GetURLStatsResponseB/Z-github.com/BohdanKuzmenko1/URLShortener;protob\x06proto3"

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData []byte
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)))
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stats_proto_goTypes = []any{
	(*GetURLStatsRequest)(nil),  // 0: stats.GetURLStatsRequest
	(*GetURLStatsResponse)(nil), // 1: stats.GetURLStatsResponse
	(*URLStats)(nil),            // 2: stats.URLStats
}
var file_stats_proto_depIdxs = []int32{
	2, // 0: stats.GetURLStatsResponse.url_stats:type_name -> stats.URLStats
	0, // 1: stats.StatsService.GetURLStats:input_type -> stats.GetURLStatsRequest
	1, // 2: stats.StatsService.GetURLStats:output_type -> stats.GetURLStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
