// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: url.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlId         int32                  `protobuf:"varint,1,opt,name=url_id,json=urlId,proto3" json:"url_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{0}
}

func (x *GetURLRequest) GetUrlId() int32 {
	if x != nil {
		return x.UrlId
	}
	return 0
}

type GetURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      *ShortURL              `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	mi := &file_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{1}
}

func (x *GetURLResponse) GetShortUrl() *ShortURL {
	if x != nil {
		return x.ShortUrl
	}
	return nil
}

type CreateShortUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUrl     string                 `protobuf:"bytes,1,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortUrlRequest) Reset() {
	*x = CreateShortUrlRequest{}
	mi := &file_url_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortUrlRequest) ProtoMessage() {}

func (x *CreateShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShortUrlRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *CreateShortUrlRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CreateShortUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortUrlResponse) Reset() {
	*x = CreateShortUrlResponse{}
	mi := &file_url_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortUrlResponse) ProtoMessage() {}

func (x *CreateShortUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortUrlResponse.ProtoReflect.Descriptor instead.
func (*CreateShortUrlResponse) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShortUrlResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ResolveSlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redirect      *URLServiceRedirect    `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSlugRequest) Reset() {
	*x = ResolveSlugRequest{}
	mi := &file_url_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSlugRequest) ProtoMessage() {}

func (x *ResolveSlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSlugRequest.ProtoReflect.Descriptor instead.
func (*ResolveSlugRequest) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveSlugRequest) GetRedirect() *URLServiceRedirect {
	if x != nil {
		return x.Redirect
	}
	return nil
}

type ResolveSlugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUrl     string                 `protobuf:"bytes,1,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSlugResponse) Reset() {
	*x = ResolveSlugResponse{}
	mi := &file_url_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSlugResponse) ProtoMessage() {}

func (x *ResolveSlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSlugResponse.ProtoReflect.Descriptor instead.
func (*ResolveSlugResponse) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveSlugResponse) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

type ShortURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlId         int32                  `protobuf:"varint,1,opt,name=url_id,json=urlId,proto3" json:"url_id,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURL) Reset() {
	*x = ShortURL{}
	mi := &file_url_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURL) ProtoMessage() {}

func (x *ShortURL) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURL.ProtoReflect.Descriptor instead.
func (*ShortURL) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{6}
}

func (x *ShortURL) GetUrlId() int32 {
	if x != nil {
		return x.UrlId
	}
	return 0
}

func (x *ShortURL) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *ShortURL) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ShortURL) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type URLServiceRedirect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Referer       string                 `protobuf:"bytes,5,opt,name=referer,proto3" json:"referer,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLServiceRedirect) Reset() {
	*x = URLServiceRedirect{}
	mi := &file_url_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLServiceRedirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLServiceRedirect) ProtoMessage() {}

func (x *URLServiceRedirect) ProtoReflect() protoreflect.Message {
	mi := &file_url_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLServiceRedirect.ProtoReflect.Descriptor instead.
func (*URLServiceRedirect) Descriptor() ([]byte, []int) {
	return file_url_proto_rawDescGZIP(), []int{7}
}

func (x *URLServiceRedirect) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *URLServiceRedirect) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *URLServiceRedirect) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *URLServiceRedirect) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *URLServiceRedirect) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *URLServiceRedirect) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_url_proto protoreflect.FileDescriptor

const file_url_proto_rawDesc = "" +
	"\n" +
	"\turl.proto\x12\x03url\"&\n" +
	"\rGetURLRequest\x12\x15\n" +
	"\x06url_id\x18\x01 \x01(\x05R\x05urlId\"<\n" +
	"\x0eGetURLResponse\x12*\n" +
	"\tshort_url\x18\x01 \x01(\v2\r.url.ShortURLR\bshortUrl\"J\n" +
	"\x15CreateShortUrlRequest\x12\x1d\n" +
	"\n" +
	"target_url\x18\x01 \x01(\tR\ttargetUrl\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"5\n" +
	"\x16CreateShortUrlResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"I\n" +
	"\x12ResolveSlugRequest\x123\n" +
	"\bredirect\x18\x01 \x01(\v2\x17.url.URLServiceRedirectR\bredirect\"4\n" +
	"\x13ResolveSlugResponse\x12\x1d\n" +
	"\n" +
	"target_url\x18\x01 \x01(\tR\ttargetUrl\"s\n" +
	"\bShortURL\x12\x15\n" +
	"\x06url_id\x18\x01 \x01(\x05R\x05urlId\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\xb4\x01\n" +
	"\x12URLServiceRedirect\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x18\n" +
	"\areferer\x18\x05 \x01(\tR\areferer\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage2\xcc\x01\n" +
	"\n" +
	"URLService\x12I\n" +
	"\x0eCreateShortURL\x12\x1a.url.CreateShortUrlRequest\x1a\x1b.url.CreateShortUrlResponse\x12@\n" +
	"\vResolveSlug\x12\x17.url.ResolveSlugRequest\x1a\x18.url.ResolveSlugResponse\x121\n" +
	"\x06GetURL\x12\x12.url.GetURLRequest\x1a\x13.url.GetURLResponseB/Z-github.com/BohdanKuzmenko1/URLShortener;protob\x06proto3"

var (
	file_url_proto_rawDescOnce sync.Once
	file_url_proto_rawDescData []byte
)

func file_url_proto_rawDescGZIP() []byte {
	file_url_proto_rawDescOnce.Do(func() {
		file_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_proto_rawDesc), len(file_url_proto_rawDesc)))
	})
	return file_url_proto_rawDescData
}

var file_url_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_url_proto_goTypes = []any{
	(*GetURLRequest)(nil),          // 0: url.GetURLRequest
	(*GetURLResponse)(nil),         // 1: url.GetURLResponse
	(*CreateShortUrlRequest)(nil),  // 2: url.CreateShortUrlRequest
	(*CreateShortUrlResponse)(nil), // 3: url.CreateShortUrlResponse
	(*ResolveSlugRequest)(nil),     // 4: url.ResolveSlugRequest
	(*ResolveSlugResponse)(nil),    // 5: url.ResolveSlugResponse
	(*ShortURL)(nil),               // 6: url.ShortURL
	(*URLServiceRedirect)(nil),     // 7: url.URLServiceRedirect
}
var file_url_proto_depIdxs = []int32{
	6, // 0: url.GetURLResponse.short_url:type_name -> url.ShortURL
	7, // 1: url.ResolveSlugRequest.redirect:type_name -> url.URLServiceRedirect
	2, // 2: url.URLService.CreateShortURL:input_type -> url.CreateShortUrlRequest
	4, // 3: url.URLService.ResolveSlug:input_type -> url.ResolveSlugRequest
	0, // 4: url.URLService.GetURL:input_type -> url.GetURLRequest
	3, // 5: url.URLService.CreateShortURL:output_type -> url.CreateShortUrlResponse
	5, // 6: url.URLService.ResolveSlug:output_type -> url.ResolveSlugResponse
	1, // 7: url.URLService.GetURL:output_type -> url.GetURLResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_url_proto_init() }
func file_url_proto_init() {
	if File_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_proto_rawDesc), len(file_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_proto_goTypes,
		DependencyIndexes: file_url_proto_depIdxs,
		MessageInfos:      file_url_proto_msgTypes,
	}.Build()
	File_url_proto = out.File
	file_url_proto_goTypes = nil
	file_url_proto_depIdxs = nil
}
