package handler

import (
	"context"
	"fmt"
	pb "github.com/BohdanKuzmenko1/URLShortener/proto"
	"github.com/gin-gonic/gin"
	"github.com/spf13/viper"
	"google.golang.org/grpc/metadata"
	"net/http"
	"strings"
	"time"
)

// ShortenURL creates a shortened URL for the given target URL.
// An optional custom slug can be provided; if omitted, one is generated by the URL Service.
func (h *Handler) ShortenURL(c *gin.Context) {
	var req struct {
		TargetURL string `json:"target_url" binding:"required"`
		Slug      string `json:"slug"`
	}

	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	if !strings.HasPrefix(req.TargetURL, "http://") &&
		!strings.HasPrefix(req.TargetURL, "https://") {
		c.JSON(http.StatusBadRequest, gin.H{"error": "URL must start with http:// or https://"})
		return
	}

	token := c.GetHeader("Authorization")

	ctx, cancel := context.WithTimeout(c.Request.Context(), 10*time.Second)
	defer cancel()

	ctx = metadata.NewOutgoingContext(ctx, metadata.Pairs("authorization", token))

	resp, err := h.urlServiceClient.CreateShortURL(ctx, &pb.CreateShortUrlRequest{
		TargetUrl: req.TargetURL,
		Slug:      req.Slug,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to create short URL"})
		return
	}

	c.JSON(http.StatusOK, gin.H{"short_url": resp.ShortUrl})
}

// ResolveSlug resolves a slug to its original URL and redirects the client.
// Collects request metadata (IP, User-Agent, Referer, Language) for stats tracking.
// On failure, redirects to the frontend homepage instead of returning an error.
func (h *Handler) ResolveSlug(c *gin.Context) {
	slug := c.Param("slug")

	redirect := pb.URLServiceRedirect{
		Slug:      slug,
		UserAgent: c.Request.UserAgent(),
		ClientIp:  c.ClientIP(),
		Country:   "unknown", // country := c.GetHeader("CF-IPCountry") for prod env when Cloudflare is connected
		Referer:   c.Request.Referer(),
		Language:  c.GetHeader("Accept-Language"),
	}

	ctx, cancel := context.WithTimeout(c.Request.Context(), 10*time.Second)
	defer cancel()

	resp, err := h.urlServiceClient.ResolveSlug(ctx, &pb.ResolveSlugRequest{
		Redirect: &redirect,
	})

	if err != nil {
		fmt.Printf("Failed to resolve slug %s: %v\n", slug, err)
		c.Redirect(http.StatusMovedPermanently, viper.GetString("frontend.homepage"))
		return
	}

	c.Redirect(http.StatusFound, resp.TargetUrl)
}
